apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.sharedPvc.name }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.sharedPvc.storage }}
  {{- if .Values.sharedPvc.pvName}}
  volumeName: {{ .Values.sharedPvc.pvName }}
  {{- end }}
  storageClassName: {{ .Values.sharedPvc.storageclass }}
