# Name of application
name: ecde # Name of application
localDevelopment: true
webapp:
  image: eccr.ecmwf.int/c3s-applications/ecde-webapp  # image for application
  tag: test  # image tag to use (this )
  port: 80  # Port exposed by the application
  replicas: 1
apiServer:
  image: eccr.ecmwf.int/c3s-applications/ecde-server  # image for application
  tag: latest  # image tag to use (this )
  port: 5000 # Port exposed by the application
  replicas: 1
  startupCommand: cp -r ./european_climate_data_explorer/skinnywms/* /skinnywms/ && python3 european_climate_data_explorer/preload_wms.py && make start-server API_HOST=0.0.0.0 ROOT_PATH=$ROOT_PATH
  env:
    rootPath: /
    wmsServer: http://localhost
    mode: production
    allowedOrigin: http://localhost:8080
wms:
  image: ecmwf/skinnywms  # image for application
  tag: 0.10.0  # image tag to use (this )
  port: 5001  # Port exposed by the application
  replicas: 1
  env:
    skinnywmsUwsgiWorkers: $(SKINNYWMS_UWSGI_WORKERS:-4)
commonWms:
  env:
    wmsDataDir: /skinnywms/appdata
    wmsStyleDir: /skinnywms/styles
sharedPvc:
  name: wms-data-volume
  pvName: pv-wms
  storage: 10Gi
  storageclass: nfs-csi
  path: /skinnywms
# Values used for ingress control
ingress:
  enable: false
  # Hostname where the app will be published, this must be mapped to the cluster described by the KUBECONFIG
  hostname: ecds-dev-cci2.copernicus-climate.eu  
  # Path to the application, this must be included in the env when building a JS application
  webappPath: /c3s-apps/ecde/
  apiPath: /c3s-apps/ecde/api/ 
  wmsPath: /c3s-apps/ecde/wms/ 
  # SSL certificate secret name:
  secretName: star.copernicus-climate.eu
  ingressclass: nginx-dev

# set certManagerCertificateRequest to "true" and certManager parameters to use cert-manager and acme challenge
  certManagerCertificateRequest: false
  certManager:
    clusterIssuer: letsencrypt-c3s # Cluster issuer to use for SSL certificates
    issueTemporaryCertificate: false # Set to true to issue a temporary certificate
    acme: true # Set to true to use ACME for certificate issuance
    disableSslRedirect: false # Set to true to disable SSL redirect 
