apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/configuration-snippet: rewrite ^([^.]*{{ .Values.ingress.path }}[^/])$ $1/ permanent;
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/proxy-buffer-size: 128K
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"

    # Not currently used, but here for reference if we go back to nginx.org annotations
    nginx.org/proxy-buffer-size: 128K
    nginx.org/proxy-buffers: 4 256K
    nginx.org/proxy-busy-buffers-size: 256K
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.hostname }}
      secretName: {{ .Values.ingress.secretName }}
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - pathType: ImplementationSpecific
            path: {{ .Values.ingress.path }}
            backend:
              service:
                name: {{ .Values.name }}
                port:
                  number: 80
          - pathType: ImplementationSpecific
            path: {{ .Values.ingress.path }}/(.*)
            backend:
              service:
                name: {{ .Values.name }}
                port:
                  number: 80
  ingressClassName: nginx

