{{- if .Values.ingress.certManagerCertificateRequest }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer }}
    {{- if .Values.ingress.issueTemporaryCertificate }}
    cert-manager.io/issue-temporary-certificate: "true"
    {{- end }}
    {{- if .Values.ingress.acme }}
    acme.cert-manager.io/http01-edit-in-place: "true"
    {{- end }}
    {{- if .Values.ingress.disableSslRedirect }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    {{- end }}
  name: {{ .Values.name }}-solver
spec:
  ingressClassName: {{ .Values.ingress.ingressclass }}
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Values.name }}-webapp
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ .Values.ingress.hostname }}
    secretName: {{ .Values.ingress.secretName }}
{{- end}}