apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-webapp
spec:
  selector:
    component: webapp
  type: ClusterIP
  ports:
    - name: webapp-port
      port: 80
      targetPort: {{ .Values.webapp.port }}
