apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-wms
spec:
  selector:
    component: wms
  type: ClusterIP
  ports:
    - name: wms-port
      port: {{ .Values.wms.port }}
      targetPort: {{ .Values.wms.port }}
