apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-wms
spec:
  replicas: {{ .Values.wms.replicas }}
  selector:
    matchLabels:
      component: wms
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        component: wms
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}-wms
          args:
          - bash
          - -c
          - while true; do if [ -f {{ .Values.commonWms.env.wmsDataDir }}/.completed.txt ]; then echo ".completed.txt found"; break; else echo "Waiting for .completed.txt creation..."; sleep 1; fi; done; echo "Verification succeeded!" && uwsgi --http 0.0.0.0:$WMS_PORT --master --mount /=skinnywms.wmssvr:application --env SKINNYWMS_DATA_PATH=./$WMS_DATA --env MAGICS_STYLE_PATH=./$WMS_STYLES
          image: {{ .Values.wms.image }}:{{ .Values.wms.tag }}
          ports:
            - containerPort: {{ .Values.wms.port }}
          env:
          - name: WMS_PORT
            value: $(ECDE_WMS_SERVICE_PORT_WMS_PORT)
          - name: WMS_DATA
            value: {{ .Values.commonWms.env.wmsDataDir }}
          - name: WMS_STYLES
            value: {{ .Values.commonWms.env.wmsStyleDir }}
          volumeMounts:
          - mountPath: {{ .Values.sharedPvc.path }}
            name: {{ .Values.sharedPvc.name }}
      volumes:
      - name: {{ .Values.sharedPvc.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.sharedPvc.name }}
