apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-api
spec:
  selector:
    component: api
  type: ClusterIP
  ports:
    - name: api-port
      port: {{ .Values.apiServer.port }}
      targetPort: {{ .Values.apiServer.port }}
