{{- if .Values.sharedPvc }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.sharedPvc.name }}
spec:
  provisioner: nfs.csi.k8s.io
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.sharedPvc.storage }}
  storageClassName: "{{ .Values.sharedPvc.storageclass }}-{{ .Values.name }}"
{{- end }}
