apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "{{ .Values.sharedPvc.storageclass }}-{{ .Values.name }}"
provisioner: nfs.csi.k8s.io
parameters:
  server: {{ .Values.sharedPvc.nfsServerUrl }}
  share: /
  subDir: {{ .Values.name }}
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.1
